### ISSUE TITLE
Double callback bug when using await in `request.get().end()`

### ISSUE THREAD

**Issue by Azard** [visionmedia/superagent#1121]
My code run well like:
``` JavaScript
const getBrands = () => {
  request
  .get([URL, BrandsPage].join('/'))
  .end((err, res) => {
    let $ = cheerio.load(res.text);
    $('a', '.st-text').each((i, elem) => {
      // do something
    });
  })
};
```

But when I use Node.js 7.2.0 ES7 harmony flag `await` :
``` JavaScript
const getBrands = async () => {
  await request
  .get([URL, BrandsPage].join('/'))
  .end((err, res) => {
    let $ = cheerio.load(res.text);
    $('a', '.st-text').each((i, elem) => {
      // do something
    });
  })
};

getBrands()
.then(v => console.log(v))
.catch(e => console.log(e));
```

``` Shell
{ Error: incorrect header check
    at Zlib._handle.onerror (zlib.js:355:17) errno: -3, code: 'Z_DATA_ERROR', response: null }
superagent: double callback bug
```

And the detail error is:
```
Error: superagent: double callback bug
    at Request.callback (/Users/azard/appetizerio/gsmarenacrawler/node_modules/superagent/lib/node/index.js:628:26)
    at Stream.<anonymous> (/Users/azard/appetizerio/gsmarenacrawler/node_modules/superagent/lib/node/index.js:833:18)
    at emitNone (events.js:91:20)
    at Stream.emit (events.js:185:7)
    at Unzip.<anonymous> (/Users/azard/appetizerio/gsmarenacrawler/node_modules/superagent/lib/node/utils.js:112:12)
    at emitNone (events.js:91:20)
    at Unzip.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

https://github.com/visionmedia/superagent/issues/957 said superagent support async/await, why I can't use await in `request.get().end()` ?

**Comment by pornel** [comment]
You can't use `end()` if you're using promises. 

     await request.get()

**Comment by Azard** [comment]
@pornel But how can I get the `GET` response in async/await model ?

**Comment by pornel** [comment]
It will be returned, so

```js
const response = await request.get(…);
```

**Comment by Azard** [comment]
@pornel Thank you, it's OK 😃
