### ISSUE TITLE
superagent-no-cache sue error

### ISSUE THREAD

**Issue by zhoudaqing** [visionmedia/superagent#1204]
const nocache = require('superagent-no-cache');
const request = require('superagent');

request
        .get('/test')
        .use(nocache)
        .end(function(err, res){
         });

error:
============================================
/Users/akk/sourcecode/test/node_modules/component-ie/index.js:16
           el = document.createElement('b'),
                         ^

ReferenceError: document is not defined
    at ie (/Users/akk/sourcecode/test/node_modules/component-ie/index.js:16:26)
    at Object.<anonymous> (/Users/akk/sourcecode/test/node_modules/component-ie/index.js:5:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/akk/sourcecode/test/node_modules/superagent-no-cache/index.js:1:72)

Process finished with exit code 1

**Comment by pornel** [comment]
I can't fix this. Please report the problem to the author of "superagent-no-cache" plugin.
