### ISSUE TITLE
redirect 302 is crashed

### ISSUE THREAD

**Issue by runhwguo** [visionmedia/superagent#1208]
**Trace: { Error: Found**
    at Request.callback (/Users/runhwguo/project/test/nodejsWeb/node_modules/superagent/lib/node/index.js:675:11)
    at IncomingMessage.<anonymous> (/Users/runhwguo/project/test/nodejsWeb/node_modules/superagent/lib/node/index.js:883:18)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  **status: 302,**
  response: 
   Response {
     domain: null,
     _events: {},
     _eventsCount: 0,
     _maxListeners: undefined,
     res: 
      IncomingMessage {
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 4,

it confuse me a lot!

**Comment by pornel** [comment]
This happens when there were too many redirects.

**Comment by runhwguo** [comment]
yeah，i get it，thank you
