### ISSUE TITLE
superagent upload

### ISSUE THREAD

**Issue by luck-zzb** [visionmedia/superagent#1237]
```js
import convert from 'koa-convert';
import request from 'superagent';
const promisePipe = require('promisepipe');
import config from '../../config';
const fs = require('fs');
const is = require('is-type-of');
const parse = require('co-busboy');


const put = function* put(name, file) {
  let content;

  try {
 if (is.readableStream(file)) {
      console.log('is readableStream==');
      const req = request.post('http://127.0.0.1:8081/rule/testUpload').set('Transfer-Encoding', 'chunked').timeout(5000);
      yield file.pipe(req, { end: false }).on('error', (err) => {
        console.log('file.pipe error===========>', err);
      }).on('end', (err, res) => {
        console.log('file.pipe end err===========>', err);
        console.log('file.pipe end res===========>', res);
      });
    } else {
      throw new TypeError('Must provide String/Buffer/ReadableStream for put.');
    }
    console.log('return==');
  } catch (e) {
    console.log(e);
  }
};


const uploadFile = convert(function* (next) {
  console.log('next============>', next);
  console.log('this============>', this);
  // the body isn't multipart, so busboy can't parse it
  if (!this.request.is('multipart/*')) return yield next;

  const parts = parse(this);
  let part;
  let aliyunOss;
  try {
    while (part = yield parts) {
      console.log('file part', part);
      if (part && part.filename) {
        const res = yield put(part.filename, part);
        console.log('yield put res=========>', res);
      }
    }
  } catch (e) {
    console.log(e);
  }
```

想用ant-design + superagent上传文件  新手，前端大神帮看下
报异常
> Error: write after end
    at ClientRequest.OutgoingMessage.write (_http_outgoing.js:439:15)
    at Request.write (D:\react\phoenix20170309_11934_1\node_modules\superagent\lib\node\index.js:331:14)
    at FileStream.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at FileStream.emit (events.js:188:7)
    at FileStream.Readable.read (_stream_readable.js:381:10)
    at flow (_stream_readable.js:761:34)
    at resume_ (_stream_readable.js:743:3)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by pornel** [comment]
We don't support piping of uploads. You must use `.attach()` to upload a file.

**Comment by luck-zzb** [comment]
Thanks for the answer @pornel

**Comment by isaachinman** [comment]
@kornelski Is this still the case? There's no way to test stream uploads?

**Comment by isaachinman** [comment]
Do you mind explaining the reasoning behind that?

**Comment by kornelski** [comment]
You can use streams to upload files, just not with `.pipe()`, but with `.attach()`. We use [`FormData`](https://www.npmjs.com/package/form-data#usage) to handle this.

That's just our API — `multipart` forms are handled via `.field()` & `.attach()`, and "raw data" is handled by `.send()` or `.pipe()`.

**Comment by ian-speers** [comment]
@kornelski if this is the case — would it be possible to update [the documentation](https://visionmedia.github.io/superagent/#piping-data)? I just burned an hour trying to get the `Piping data` example to work.

**Comment by kornelski** [comment]
What about this example is wrong?

**Comment by ian-speers** [comment]
The code throws a `write after end` error:

```js
const superagent = require('superagent');
const fs = require('fs');

const inStream = fs.createReadStream('in.json');
const outStream = fs.createWriteStream('out.json');
const request = superagent.post('https://postman-echo.com/post');

request.type('json');
inStream.pipe(request).pipe(outStream);
```

```
Error: write after end
    at write_ (_http_outgoing.js:622:15)
    at ClientRequest.write (_http_outgoing.js:617:10)
    at Request.write (.../node_modules/superagent/lib/node/index.js:384:14)
    at ReadStream.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at ReadStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at ReadStream.Readable.push (_stream_readable.js:208:10)
    at fs.read (fs.js:2058:12)
```
