### ISSUE TITLE
"double callback bug" with Range header

### ISSUE THREAD

**Issue by freitagbr** [visionmedia/superagent#1252]
`superagent` version: `3.5.2`
`supertest` version: `3.0.0`
`node` version: `6.10.3`

I am using `supertest` to test a file download API. This API accepts the `Range` header. While testing this API, I noticed that `superagent` shows a `double callback bug` when the `Range` header is set. Here is an example test case that will cause this error:
```js
'use strict';

const fs = require('fs');
const path = require('path');

const app = require('express')();
const request = require('supertest')(app);

// set up download route that responds with
// the content of this file
app.get('/download', (req, res, next) => {
  fs.stat(__filename, (err, stats) => {
    const size = stats.size;
    let range = req.range(size);
    let start = 0;
    let end = size;

    if (Array.isArray(range) && range.type === 'bytes') {
      range = range[0];
      start = range.start;
      end = range.end;
      res.status(206);
      res.setHeader('Content-Range', `bytes ${start}-${end}/${size}`);
      res.setHeader('Accept-Ranges', 'bytes');
    }

    const filename = path.basename(__filename);
    const stream = fs.createReadStream(__filename, { start, end });

    res.setHeader('Content-Disposition', `attachment; filename=${filename}`);
    res.setHeader('Content-Length', end - start);
    res.setHeader('Content-Type', 'text/plain');

    stream.pipe(res);
  });
});

request.get('/download')
  .set('Range', 'bytes=10-20') // this Range causes an error
  // .set('Range', 'bytes=10-') // this Range works
  .expect(206)
  .end((err) => {
    console.log(err);
  });
```

This is the result:
```
$ node index.js
TypeError: Cannot read property 'status' of undefined
    at Test._assertStatus (/usr/src/tmp/node_modules/supertest/lib/test.js:263:10)
    at Test._assertFunction (/usr/src/tmp/node_modules/supertest/lib/test.js:281:11)
    at Test.assert (/usr/src/tmp/node_modules/supertest/lib/test.js:171:18)
    at Server.assert (/usr/src/tmp/node_modules/supertest/lib/test.js:131:12)
    at Server.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Server.emit (events.js:185:7)
    at emitCloseNT (net.js:1554:8)
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
superagent: double callback bug
```

Note: the test passes if `'Range'` is set to `'bytes=10-'`, i.e. missing the end range.

**Comment by freitagbr** [comment]
Nevermind, the issue is not with `superagent`. The issue was that the `Content-Length` header was not being set correctly; `bytes=10-20` is inclusive, so the `Content-Length` should be `11`, not `10`.
