### ISSUE TITLE
BUG: "ERROR: First argument must be a string or Buffer" for content-type:"text/plain" and body defined

### ISSUE THREAD

**Issue by ChrisCinelli** [visionmedia/superagent#1263]
If you call a `.send()` with a value, you set `content-type:"text/plain"` in the headers  and the response of the request is a 4xx, `superagent` does not return the result of the request.

Notice that for the request `#2` status is `undefined`

```
$ node superagent.test.js
1 ') superagent calling' '{"content-type":"text/plain"}' undefined
2 ') superagent calling' '{"content-type":"text/plain"}' '{"foo":1}'
3 ') superagent calling' '{}' undefined
4 ') superagent calling' '{}' '{"foo":1}'
2 ') superagent catch -> status ==>' undefined
TypeError: First argument must be a string or Buffer
    at ClientRequest.OutgoingMessage.end (_http_outgoing.js:558:11)
    at Request._end (superagent-test/node_modules/superagent/lib/node/index.js:961:9)
    at Request.end (superagent-test/node_modules/superagent/lib/node/index.js:761:15)
    at superagent-test/node_modules/superagent/lib/request-base.js:194:12
    at Request.then (superagent-test/node_modules/superagent/lib/request-base.js:193:31)
    at makeACall (superagent-test/superagent.test.js:19:11)
    at Server.<anonymous> (superagent-test/superagent.test.js:34:5)
    at Server.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Server.emit (events.js:185:7)

1 ') superagent catch -> status ==>' 400
Error: Bad Request
    at Request.callback (superagent-test/node_modules/superagent/lib/node/index.js:675:11)
    at IncomingMessage.<anonymous> (superagent-test/node_modules/superagent/lib/node/index.js:883:18)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

3 ') superagent catch -> status ==>' 400
Error: Bad Request
    at Request.callback (superagent-test/node_modules/superagent/lib/node/index.js:675:11)
    at IncomingMessage.<anonymous> (superagent-test/node_modules/superagent/lib/node/index.js:883:18)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

4 ') superagent catch -> status ==>' 400
Error: Bad Request
    at Request.callback (superagent-test/node_modules/superagent/lib/node/index.js:675:11)
    at IncomingMessage.<anonymous> (superagent-test/node_modules/superagent/lib/node/index.js:883:18)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

This is the code I used:
```
const agent = require("superagent");

const express = require('express')
const app = express()
app.get('/', function (req, res) {
  res.status(400).end("not good");
})
var mockPort;

var callCounter = 0;

function makeACall(headers, body) {
  var _callCounter = ++callCounter;
  var request = agent('GET', "http://127.0.0.1:" + mockPort + "/");
  request.set(headers);
  request.send(body);
  console.log(_callCounter, ') superagent calling', JSON.stringify(headers), JSON.stringify(body));

  request.then(function (res) {
    console.log(_callCounter, ') superagent body ->', res.body);
  })
  .catch(function (err){
    console.error(_callCounter, ') superagent catch -> status ==>', err.status);
    console.error(err.stack || err);
    console.error();
  });
}

// port 0 let operation system choose port
const listener = app.listen(0, function () {

    mockPort = listener.address().port;
    makeACall({"content-type":"text/plain"});
    makeACall({"content-type":"text/plain"}, {foo: 1});
    makeACall({});
    makeACall({}, {foo: 1});
});
```

**Comment by focusaurus** [comment]
The response for non-200 responses is available on the error object: `err.response.text` will have the value your express server sent as the response body.

**Comment by ChrisCinelli** [comment]
For request `#2` `err.response` is `undefined`

**Comment by focusaurus** [comment]
Which version of superagent?

**Comment by ChrisCinelli** [comment]
I installed with `superagent:'*'` in the `package.json`.

**Comment by focusaurus** [comment]
OK can you look at `node_modules/superagent/package.json` for the version field please? Your stack trace is not current master.

For your error, the problem is your are explicitly setting text/plain content type then passing in an object for the body. You need to pass a string or buffer, or stringify your object explicitly.

**Comment by ChrisCinelli** [comment]
`"version": "3.5.2"`

**Comment by focusaurus** [comment]
OK so yeah the `TypeError` is when your request body object gets passed unmodified to the node `OutgoingMessage.end` method, which expects a `String` or `Buffer`.  Superagent auto-serialization only handles `application/json` and `application/x-www-form-urlencoded` content types. Other than that, you have to serialize your request body manually.

**Comment by ChrisCinelli** [comment]
I get it. I wonder if it should have a more graceful way to fail.

**Comment by focusaurus** [comment]
As far as the node core http API is concerned, this basic type checking and throwing an exception is their "graceful" error code. I'm OK with this as it's consistent with the node core behavior, although I'll grant you it may not score that many points for grace.
