### ISSUE TITLE
Uncatched error when using Promises

### ISSUE THREAD

**Issue by lapo-luchini** [visionmedia/superagent#1370]
```JavaScript
const req = require('superagent');
req.post('http://127.0.0.1/test')
.field({a:1,b:2})
.attach('c', 'does-not-exists.txt')
// .on('error', e => console.log('ERR', e))
.then(ok => console.log('THEN', ok))
.catch(e => console.log('CATCH', e));
```
never prints "CATCH" but rather
```
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'does-not-exists.txt'
Emitted 'error' event at:
    at FormData._formData.on.err (/home/lapo/svn/nodejs/tdoc-api/node_modules/superagent/lib/node/index.js:214:12)
    at FormData.emit (events.js:185:15)
    …
```
When using `.on('error')` it is correctly catched (and prints "ERR"), but I expected than using Promises all errors would end up there.

**Comment by lapo-luchini** [comment]
I suggest the following fix:
```diff
--- node_modules/superagent/lib/request-base.js.orig    2018-04-20 11:32:08.960725000 +0200
+++ node_modules/superagent/lib/request-base.js 2018-04-20 11:40:19.227878000 +0200
@@ -235,6 +235,7 @@
       console.warn("Warning: superagent request was sent twice, because both .end() and .then() were called. Never call .end() if you use promises");
     }
     this._fullfilledPromise = new Promise(function(innerResolve, innerReject) {
+      self.on('error', innerReject);
       self.end(function(err, res) {
         if (err) innerReject(err);
         else innerResolve(res);
```
which removes the `Unhandled 'error' event` by making explicit that Promises are managing the error.
(even though they were doing it already, by `.end` first parameter, really…)

**Comment by kornelski** [comment]
This sounds familiar. I think we've fixed such error once already. Are you using the latest version?

**Comment by lapo-luchini** [comment]
Latest NPM, v3.8.2.

On Windows (where I am now) the output is slightly different (but the same idea):
```
PS C:\Users\lapo\t> npm install superagent
+ superagent@3.8.2
added 24 packages in 1.349s
PS C:\Users\lapo\t> node test
events.js:137
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'C:\Users\lapo\t\does-not-exists.txt'
```
with patch:
```
PS C:\Users\lapo\t> node test
CATCH ENOENT: no such file or directory, open 'C:\Users\lapo\t\does-not-exists.txt'
```
