### ISSUE TITLE
using a self-signed certificate results in a request error

### ISSUE THREAD

**Issue by budarin** [visionmedia/superagent#1376]
I use to self signed certificate for dev.
In node code I try to get some recources from the same domain on another port
```js
import request from 'superagent';
...
const key = fs.readFileSync('certs/server.key');
const cert = fs.readFileSync('certs/server.crt');
....
       try {
            const agent = request.agent();
            const response = await agent
                .get(runtimeUrl)
                .key(key)
                .cert(cert)
                .buffer(true);

            return response.text;
        } catch (error) {
            logError(error);
        }
```

but get error:
```
Error: unable to verify the first certificate
[1]     at TLSSocket.onConnectSecure (_tls_wrap.js:1060:34)
[1]     at TLSSocket.emit (events.js:182:13)
[1]     at TLSSocket._finishInit (_tls_wrap.js:639:8) code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE', response: undefined }
```

**Comment by budarin** [comment]
Thanks! It helped!

**Comment by budarin** [comment]
I make a request to ```https://192.168.10.103:44300``` - here is webpack-dev-server

**Comment by budarin** [comment]
I'm sorry - I have found solution: instead of using IP it should be used machine name!
Thanks!
