### ISSUE TITLE
browserify/es5 not working? lib/client.js should be compiled for browsers?

### ISSUE THREAD

**Issue by niftylettuce** [visionmedia/superagent#1418]
when building a third party package that has both client and server side approach I attempted to add this to my `package.json`:

> this is the default behavior since this is already in the `browser` field of `package.json` in `superagent` here <https://github.com/visionmedia/superagent/blob/master/package.json#L57>

```sh
  "browser": {
    "superagent": "superagent/lib/client.js"
  },
```

I also tried this:

```sh
  "browser": {
    "superagent": "superagent/superagent.js"
  },
```

The first yields this error:

```sh
> cross-env NODE_ENV=production browserify src/index.js -o dist/beep.min.js -s Beep -d -t babelify -p tinyify

SyntaxError: Unexpected token (1:684)
    at Parser.pp$4.raise (/Users/user/Projects/my-project/node_modules/acorn/dist/acorn.js:2757:13)
    at Parser.pp.unexpected (/Users/user/Projects/my-project/node_modules/acorn/dist/acorn.js:647:8)
    at Parser.pp.semicolon (/Users/user/Projects/my-project/node_modules/acorn/dist/acorn.js:624:64)
    at Parser.pp$1.parseExpressionStatement (/Users/user/Projects/my-project/node_modules/acorn/dist/acorn.js:1093:8)
    at Parser.pp$1.parseStatement (/Users/user/Projects/my-project/node_modules/acorn/dist/acorn.js:818:24)
    at Parser.parseStatement (/Users/user/Projects/my-project/node_modules/acorn-dynamic-import/lib/inject.js:47:31)
    at Parser.parseStatement (/Users/user/Projects/my-project/node_modules/acorn-node/lib/import-meta/index.js:40:55)
    at Parser.pp$1.parseTopLevel (/Users/user/Projects/my-project/node_modules/acorn/dist/acorn.js:706:23)
    at Parser.parse (/Users/user/Projects/my-project/node_modules/acorn/dist/acorn.js:551:15)
    at Object.parse (/Users/user/Projects/my-project/node_modules/acorn/dist/acorn.js:5288:37)
```

And the second:

```sh
> beep@0.0.1 browserify /Users/user/Projects/my-project
> browserify src/index.js -o dist/beep.js -s Beep -d -t babelify

Error: Cannot find module './is-object' from '/Users/user/Projects/my-project/node_modules/superagent'
    at /Users/user/Projects/my-project/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/Users/user/Projects/my-project/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/user/Projects/my-project/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /Users/user/Projects/my-project/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
```

**Comment by niftylettuce** [comment]
As soon I removed the `-p tinyify` flag with `browserify` it went away.  Seems like a weird parsing issue with `tinyify`.

**Comment by niftylettuce** [comment]
I've narrowed the issue down to <https://github.com/visionmedia/superagent/blob/master/lib/utils.js>:

```sh
> cross-env NODE_ENV=production browserify src/index.js -o dist/beep.min.js -s Beep -d -t babelify -p tinyify

loc Position { line: 1, column: 684 }
this.input "use strict";exports.type=(str=>str.split(/ *; */).shift()),exports.params=(str=>str.split(/ *; */).reduce((obj,str)=>{const parts=str.split(/ *= */),key=parts.shift(),val=parts.shift();return key&&val&&(obj[key]=val),obj},{})),exports.parseLinks=(str=>str.split(/ *, */).reduce((obj,str)=>{const parts=str.split(/ *; */),url=parts[0].slice(1,-1);return obj[parts[1].split(/ *= */)[1].slice(1,-1)]=url,obj},{})),/* common-shake removed: exports.cleanHeader = */ void 0, (header,changesOrigin)=>(delete header["content-type"],delete header["content-length"],delete header["transfer-encoding"],delete header.host,changesOrigin&&(delete header.authorization,delete header.cookie),header));

pos 684
this.pos 685
SyntaxError: Unexpected token (1:684)
    at Parser.pp$4.raise (/Users/user/Projects/my-project/node_modules/acorn/dist/acorn.js:2761:13)
    at Parser.pp.unexpected (/Users/user/Projects/my-project/node_modules/acorn/dist/acorn.js:647:8)
    at Parser.pp.semicolon (/Users/user/Projects/my-project/node_modules/acorn/dist/acorn.js:624:64)
    at Parser.pp$1.parseExpressionStatement (/Users/user/Projects/my-project/node_modules/acorn/dist/acorn.js:1093:8)
    at Parser.pp$1.parseStatement (/Users/user/Projects/my-project/node_modules/acorn/dist/acorn.js:818:24)
    at Parser.parseStatement (/Users/user/Projects/my-project/node_modules/acorn-dynamic-import/lib/inject.js:47:31)
    at Parser.parseStatement (/Users/user/Projects/my-project/node_modules/acorn-node/lib/import-meta/index.js:40:55)
    at Parser.pp$1.parseTopLevel (/Users/user/Projects/my-project/node_modules/acorn/dist/acorn.js:706:23)
    at Parser.parse (/Users/user/Projects/my-project/node_modules/acorn/dist/acorn.js:551:15)
    at Object.parse (/Users/user/Projects/my-project/node_modules/acorn/dist/acorn.js:5292:37)
```

**Comment by niftylettuce** [comment]
`.babelrc`:

```json
{
  "presets": [
    ["@babel/env", {
      "targets": {
        "node": "6.4.0",
        "browsers": [ "> 1%", "last 2 versions", "ie >= 9" ]
      }
    }]
  ],
  "sourceMaps": "inline"
}
```

**Comment by niftylettuce** [comment]
seems to be an issue with common-shakeify so opening an issue there https://github.com/browserify/common-shakeify/issues/18

**Comment by ksmith97** [comment]
Note that for babel 7.x .babelrc will no longer apply to sub projects. You need to create a babel.config.js file for global (configuration)[https://babeljs.io/docs/en/next/config-files].  You can see that you still have arrow functions in your output which is obviously not going to work with IE

**Comment by niftylettuce** [comment]
Preset env is used so arrow functions get converted

**Comment by niftylettuce** [comment]
see my PR opened which resolves this

**Comment by niftylettuce** [comment]
v5.0.0 is released and fixes this issue
