### ISSUE TITLE
Bug when parsing JSON in superagent/lib/node/parsers/json.js 

### ISSUE THREAD

**Issue by DaggieBlanqx** [visionmedia/superagent#1448]
I am using a WordPress API module in  NodeJS ( https://github.com/WP-API/node-wpapi )
When I make API requests ; it gets the json data , but causes an error . 
When I open the stacktrace : 

` { SyntaxError: Unexpected token ﻿ in JSON at position 0
at JSON.parse (<anonymous>)
  at IncomingMessage.res.on (C:\cde\fn\notification-stream\node_modules\superagent\lib\node\parsers\json.js:11:35)
   at IncomingMessage.emit (events.js:187:15)
   at endReadableNT (_stream_readable.js:1092:12)
   at process._tickCallback (internal/process/next_tick.js:63:19) `

When I examine the file `superagent/lib/node/parsers/json.js ` , I found a bug in how it parses JSON .

**Comment by DaggieBlanqx** [comment]
> I am using a WordPress API module in NodeJS ( https://github.com/WP-API/node-wpapi )
> When I make API requests ; it gets the json data , but causes an error .
> When I open the stacktrace :
> 
> `{ SyntaxError: Unexpected token ﻿ in JSON at position 0 at JSON.parse (<anonymous>) at IncomingMessage.res.on (C:\cde\fn\notification-stream\node_modules\superagent\lib\node\parsers\json.js:11:35) at IncomingMessage.emit (events.js:187:15) at endReadableNT (_stream_readable.js:1092:12) at process._tickCallback (internal/process/next_tick.js:63:19)`
> 
> When I examine the file `superagent/lib/node/parsers/json.js ` , I found a bug in how it parses JSON .

I have figured out by a simple if statement to ensure that res.text is a string ; so we can run JSON.parse() to make it an Object

`'use strict';

module.exports = function parseJSON(res, fn){
  res.text = '';
  res.setEncoding('utf8');
  res.on('data', chunk => {
    res.text += chunk;
  });
  res.on('end', () => {
    try {
      //EDIT : before passing JSON ensure its typeof String
     if (typeof res.text != String) {
        res.text = JSON.stringify(res.text);
      }
      //END OF EDIT : now we are sure that res.text is typeof String
      var body = JSON.parse(res.text);
    } catch (e) {
      var err = e;
      // issue #675: return the raw response if the response parsing fails
      err.rawResponse = res.text || null;
      // issue #876: return the http status code if the response parsing fails
      err.statusCode = res.statusCode;
    } finally {
      fn(err, body);
    }
  });
};
`
