### ISSUE TITLE
Requesting http/2 server with valid key and cert leads to ERR_HTTP2_STREAM_CANCEL, unable to verify the first certificate

### ISSUE THREAD

**Issue by desmap** [visionmedia/superagent#1461]
I have a node http/2 server running with valid key and cert on the server side, Chrome shows me: 
![image](https://user-images.githubusercontent.com/43666255/53068677-95f63900-34d9-11e9-8192-dc036447d52c.png)

When I request this server with...
```
require('superagent')
  .get('https://example.com:8443')
  .http2()
  .then((err, res) => { console.log(res) })
```
...I get `Error [ERR_HTTP2_STREAM_CANCEL]: The pending stream has been canceled (caused by: unable to verify the first certificate)`. To what does latter refer?

Full error message:
```
Promise {
  <pending>,
  domain:
   Domain {
     domain: null,
     _events:
      [Object: null prototype] {
        removeListener: [Function: updateExceptionCapture],
        newListener: [Function: updateExceptionCapture],
        error: [Function: debugDomainError] },
     _eventsCount: 3,
     _maxListeners: undefined,
     members: [] } }
> superagent: double callback bug
(node:14963) UnhandledPromiseRejectionWarning: Error [ERR_HTTP2_STREAM_CANCEL]: The pending stream has been canceled (caused by: unable to verify the first certificate)
    at ClientHttp2Session.destroy (internal/http2/core.js:1219:20)
    at TLSSocket.socketOnError (internal/http2/core.js:2605:13)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket.EventEmitter.emit (domain.js:441:20)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:14963) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14963) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by desmap** [comment]
Solved, reason was: my server cert was missing the CA Intermediate Cert (which can be found on the CA website and has to be pasted just the line after your domains cert). Closing.
