### ISSUE TITLE
UNABLE_TO_GET_ISSUER_CERT_LOCALLY

### ISSUE THREAD

**Issue by lumos102** [visionmedia/superagent#1485]
I require superagent and use it  in app.js，add when I run `node app.js`，it shows `UNABLE_TO_GET_ISSUER_CERT_LOCALLY`

**Comment by lumos102** [comment]
{ Error: unable to get local issuer certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1116:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:643:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:473:38)
  code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY',
  response: undefined }

**Comment by niftylettuce** [comment]
This seems to be a local issue for you, if you can provide a reproducible test case or more information let us know.
