### ISSUE TITLE
certificate has expired

### ISSUE THREAD

**Issue by lnts2015** [visionmedia/superagent#1567]
use "superagent": "^4.0.0",

my code : 
`
superagent.get('https://xxx.net/a.json')
    .end((err,info)=>{
    console.error(err);
    console.info(info);
});
`

error info：
```

{ Error: certificate has expired
    at TLSSocket.<anonymous> (_tls_wrap.js:1116:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:643:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:473:38) code: 'CERT_HAS_EXPIRED', response: undefined }
```

**Comment by niftylettuce** [comment]
This is not a bug with superagent.  The certificate of the server you are sending a request to has expired and needs renewed.
