### ISSUE TITLE
body not being returned on 500

### ISSUE THREAD

**Issue by sintaxi** [visionmedia/superagent#304]
to reproduce, put this in file `test.js`...

``` js
var http    = require('http')
var assert  = require('assert')
var agent   = require('superagent')

http.createServer(function (req, res) {
  res.writeHead(500, {'Content-Type': 'text/plain'})
  res.end('Hello World\n')
}).listen(1337, '127.0.0.1', function(){
  agent.get('http://127.0.0.1:1337/').end(function(err, response){
    assert.equal(response.status, 500)
    assert.equal(response.body, 'Hello World\n')
  })
})
```

the response...

```
assert.js:92
  throw new assert.AssertionError({
        ^
AssertionError: {} == "Hello World\n"
    at /Users/sintaxi/Desktop/agenttest/test.js:11:12
    at Request.callback (/Users/sintaxi/Desktop/agenttest/node_modules/superagent/lib/node/index.js:628:30)
    at Request.<anonymous> (/Users/sintaxi/Desktop/agenttest/node_modules/superagent/lib/node/index.js:131:10)
    at Request.EventEmitter.emit (events.js:95:17)
    at IncomingMessage.<anonymous> (/Users/sintaxi/Desktop/agenttest/node_modules/superagent/lib/node/index.js:773:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
```

running node v0.10.17

**Comment by noah79** [comment]
I have the same problem:

![image](https://cloud.githubusercontent.com/assets/2080870/22748780/384e564e-edf9-11e6-92f8-3f9519f5868d.png)

.content and .body are both undefined.

**Comment by pornel** [comment]
This is intentional. You can use the new `.ok(status => true)` function to ignore errors.
