### ISSUE TITLE
Formidable "stream ended unexpectedly" sometimes

### ISSUE THREAD

**Issue by aseemk** [visionmedia/superagent#377]
I'm using Superagent to upload an image to our Express 3 / Connect 2 app, using the built-in multipart parser powered by Formidable.

Here's my Superagent code:

```js
req = superagent
    .post(url)
    .auth(username, password)
    .attach('image', imagePath)

if (foo)
    req.field('foo', foo.bar)

req.end(callback)
```

This sometimes works fine, but other times, Formidable throws an error which makes it seem like Superagent didn't upload the full image?

```
Error: MultipartParser.end(): stream ended unexpectedly: state = PART_DATA 
  at MultipartParser.end (/app/node_modules/express/node_modules/connect/node_modules/formidable/lib/multipart_parser.js:318:12) 
  at IncomingMessage.<anonymous> (/app/node_modules/express/node_modules/connect/node_modules/formidable/lib/incoming_form.js:117:30) 
  at IncomingMessage.EventEmitter.emit (events.js:92:17) 
  at _stream_readable.js:920:16 
  at process._tickCallback (node.js:415:13) 
```

I'm not sure how to debug this, because it doesn't seem to repro deterministically, but thought I would post this for now to track this issue.

**Comment by defunctzombie** [comment]
Maybe something is killing the connection? If you can provide a sample repo showing the failure it would make it easier to help you debug this. Or a failing test in the test suite.
