### ISSUE TITLE
ECONNRESET on premature res.send?

### ISSUE THREAD

**Issue by derjust** [visionmedia/superagent#543]
I have the following Express application handling uploads - wrapped in a testcase
```javascript
var multiparty = require('multiparty');var express = require('express');var morgan = require('morgan');var errorhandler = require('errorhandler');

var request = require('supertest');

var port = 8080;

describe('This sends an attachment to express while the result is delivered earlier', function() {

	before(function() {
		console.log('Starting server');
		var app = express();
		app.use(morgan("combined")); app.use(errorhandler())

	    app.post('/upload', function(req, res, next) {
	    	if (req.query.something === undefined) {
	    		//Don't care for the upload itself
	            res.header('Connection', 'close');
	    		return res.status(400).send("'something' missing");
	    	} else {
	            var form = new multiparty.Form({});
            	form.on('error', function(err) {
	                return send(500, err);
	            });

                form.on('part', function(part) {
	                console.log('Found part ' + part.name);
	                if (part.name === 'files[]') { 
	                    console.log('Received file ' + part.filename)
	                    //Just consume the stream
	                    part.resume();
	                    part.on('end', function(){
	                    	res.status(200).send(req.query.something);	
	                    });
	                } else {
	                    console.log('sends unexpected part ' + part.name);
	                    // NOTE: if you want to ignore it, just call "part.resume()"
	                    part.resume();
	                }
	            });
	            // Parse req
	            form.parse(req);
            }
	    });
		app.listen(port);
	});


	it('Should gracefully result in a 400 received from the server', function(done){
	    var req = request('http://localhost:' + port).post('/upload')
	        .set('Accept', 'application/json, text/javascript, */*; q=0.01')
	        .attach("files[]", __dirname + '/closedConnection.js', 'closedConnection.js')
	        .expect(400).end(function (err, res) {
	            if (err) {
	                return done(err);
	            }
	            done();
	        });
	});

	it('Should result in a 200 received from the server', function(done){
	    var req = request('http://localhost:' + port).post('/upload?something=abc')
	        .set('Accept', 'application/json, text/javascript, */*; q=0.01')
	        .attach("files[]", __dirname + '/closedConnection.js', 'closedConnection.js')
	        .expect(200).end(function (err, res) {
	            if (err) {
	                return done(err);
	            }
	            done();
	        });
	});
});
```
The case for handling a premature upload with a 400 works fine in browsers.

In superagent the first testcase always fails with 
```
$ mocha functionaltest/closedConnection.js

  Starting server
127.0.0.1 - - [10/Feb/2015:23:24:39 +0000] "POST /upload HTTP/1.1" 400 19 "-" "node-superagent/0.21.0"
.Found part files[]
Received file closedConnection.js
127.0.0.1 - - [10/Feb/2015:23:24:39 +0000] "POST /upload?something=abc HTTP/1.1" 200 3 "-" "node-superagent/0.21.0"
.

  1 passing (420ms)
  1 failing

  1) This sends an attachment to express while the result is delivered earlier Should gracefully result in a 400 received from the server:
     Error: read ECONNRESET
      at errnoException (net.js:905:11)
      at TCP.onread (net.js:559:19)
```

The problem is *not* around `res.header('Connection', 'close');` (http://stackoverflow.com/questions/18367824/how-to-cancel-http-upload-from-data-events)
The superagent fails with _and_ without this line.

**Comment by defunctzombie** [comment]
Please make a simpler test case that uses just superagent and not supertest or other libs on top.

**Comment by mleanos** [comment]
I have described an issue I'm having that's very similar to this

https://github.com/visionmedia/superagent/issues/747

There's definitely something going on here, in the form of a bug. Not yet sure if it's with superagent or supertest.
