### ISSUE TITLE
Using with Mocha and Express - getting a Type Error

### ISSUE THREAD

**Issue by dstroot** [visionmedia/superagent#649]
This worked until I just upgraded.  

```js
/**
 * Module Dependencies
 */

var app      = require('../server/app');
// var request  = require('supertest');
var request  = require('superagent');
var chai     = require('chai');      // http://chaijs.com
var expect   = chai.expect;          // http://chaijs.com/guide/styles/#expect

/**
 * Test Index Route
 */

describe('Test index.js routes', function () {
  describe('GET /', function () {
    it('should return index.html', function (done) {
      request(app)  // <- I think it's choking here when I pass it the Express app
      .get('/')
      .end(function (err, res) {
        expect(err).to.not.exist;
        expect(res).to.have.status(200);
        expect(res.type).to.equal('text/html');
        expect(res.text).to.contain('<h1>Hello!</h1>');
        done();
      });
    });
  });
});
```

```
  1) Test index.js routes GET / should return index.html:
     TypeError: function
      at urlFormat (url.js:357:11)
      at Context.<anonymous> (test/03_index.js:23:7)
```

Anyone else seeing this?

**Comment by defunctzombie** [comment]
Superagent doesn't support passing in an app. That is supertest.
