### ISSUE TITLE
Uncaught TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by markovuksanovic** [visionmedia/superagent#683]
I have a situation where one of my tests fails. The stack trace I get is:

```
     Uncaught TypeError: Cannot read property 'call' of undefined
      at Test.assert (/Users/mvuksano/devel/markovuksanovic.github.com/user-registry/node_modules/supertest/lib/test.js:227:5)
      at Server.assert (/Users/mvuksano/devel/markovuksanovic.github.com/user-registry/node_modules/supertest/lib/test.js:131:12)
      at Server.g (events.js:199:16)
      at Server.emit (events.js:104:17)
      at net.js:1419:10
      at process._tickCallback (node.js:355:11)
```

It looks like it's super test related. :)
I use node version v0.12.5 and supertest version 1.0.1

I can provide test case if needed. Feel free to drop me an email at my_github_username at gmail.com.

**Comment by defunctzombie** [comment]
Or just send a PR with a patch if this is an issue with this library.
