### ISSUE TITLE
[Bug] Protocol "http:" not supported. Expected "https:"

### ISSUE THREAD

**Issue by geekyme** [visionmedia/superagent#691]
I am using superagent on node.js to make external api calls.

I use an https agent on my requests like this:

```
const options = {
  keepAlive: true,
  keepAliveMsecs: 1000,
  maxSockets: 60,
  maxFreeSockets: 30
}

const agent = new https.Agent(options);

request
      .get(`${url}/?${q}`)
      .agent(agent)
      .end(function(){
       ....
       })
```

I'm using the above setup over all of my external api calls ( i have many of them) . All of them make calls to an api with protocol https. I am not sure why I am getting the below error occasionally.

```
Error: Protocol "http:" not supported. Expected "https:".
    at new ClientRequest (_http_client.js:75:11)
    at Object.exports.request (http.js:49:10)
    at makeRequest (/home/test/project/node_modules/newrelic/lib/instrumentation/core/http.js:298:31)
    at instrumentRequest (/home/test/project/node_modules/newrelic/lib/transaction/tracer/instrumentation/outbound.js:28:19)
    at wrapped (/home/test/project/node_modules/newrelic/lib/transaction/tracer/index.js:157:28)
    at Tracer.addSegment (/home/test/project/node_modules/newrelic/lib/transaction/tracer/index.js:67:48)
    at instrumentOutbound (/home/test/project/node_modules/newrelic/lib/transaction/tracer/instrumentation/outbound.js:19:23)
    at Object.wrappedRequest [as request] (/home/test/project/node_modules/newrelic/lib/instrumentation/core/http.js:292:14)
    at Request.request (/home/test/project/node_modules/superagent/lib/node/index.js:723:28)
    at Request.set (/home/test/project/node_modules/superagent/lib/node/index.js:274:8)
    at Request.set (/home/test/project/node_modules/superagent/lib/node/index.js:268:12)
    at Request.redirect (/home/test/project/node_modules/superagent/lib/node/index.js:643:8)
    at ClientRequest.<anonymous> (/home/test/project/node_modules/superagent/lib/node/index.js:892:19)
```

**Comment by sbrunot** [comment]
I got the exact same issue when the HTTPS URL that I'm calling redirect to an HTTP url (with a 307 status code).

**Comment by olivierto** [comment]
I'm facing the exact same issue.... how did you manage to solve this?

**Comment by davidtom** [comment]
Has anyone solved this issue??

**Comment by kornelski** [comment]
Yes, if you run:

```js
const agent = new https.Agent(options);
```

^ with http**s** in there, you're saying you want HTTPS-only agent and you refuse to handle unsafe HTTP.

So, just don't do that. Use `superagent.agent()`.

**Comment by davidtom** [comment]
Okay, thank you!

The strange thing is that I'm seeing this error while trying to make a request to an API url that does use `https`. My requests to other `https` urls go through fine, so I'm a bit confused why the one doesn't work.

I'm wondering if its a certificate issue on the part of the API owner? I'll keep looking into it and will circle back here with an update.
