### ISSUE TITLE
can I attach a readable stream ?

### ISSUE THREAD

**Issue by sprhawk** [visionmedia/superagent#704]
superagent 1.2.0

the current version has deprecated Part() function, so I use attach to post() object (with multipart/form-data Content-Type)

I want to know if I can attach readable stream to request ?

I see form-data.append can accept a stream object.

What I want:

```
var get = request.get(url);
var post = request.post(url2)
                             .attach('file', get, 'xxxx.file')
                             .end(function(err, res) {
});
```

But I got exception:

```
     undefined is not a function
     at Function.DelayedStream.create (/vagrant/node_modules/superagent/node_modules/form-data/node_modules/combined-stream/node_modules/delayed-stream/lib/delayed_stream.js:35:12)
    at FormData.CombinedStream.append (/vagrant/node_modules/superagent/node_modules/form-data/node_modules/combined-stream/lib/combined_stream.js:43:37)
    at FormData.append (/vagrant/node_modules/superagent/node_modules/form-data/lib/form_data.js:43:3)
```

Is this a wrong usage or something ?

**Comment by niftylettuce** [comment]
PR welcome with failing test
