### ISSUE TITLE
Error `PUT`ing content type `application/vnd.api+json`

### ISSUE THREAD

**Issue by patrickberkeley** [visionmedia/superagent#736]
With the request:

```js
      return request
        .put(this.deployUrl)
        .set('Authorization', 'Bearer ' + this._token())
        .accept('application/vnd.api+json')
        .type('application/vnd.api+json')
        .send(params)
        .end(function(err, res){
          if (err) {
            var errorMessage = 'Unable to upload: ' + err.stack;
            reject(new SilentError(errorMessage));
          } else {
            resolve();
          }
        });
```

The following error is caught:

```
upload fail TypeError: first argument must be a string or Buffer
    at ClientRequest.OutgoingMessage.end (_http_outgoing.js:512:11)
    at Request.end (/Users/patrickberkeley/Code/app/node_modules/deploy-this/node_modules/superagent/lib/node/index.js:1020:9)
```
Without setting `accept` and `type` I get a 415 response from the server. When they are set, the server doesn't respond and it seems as though superagent doesn't send the request at all because `end()` never gets called.

**Comment by patrickberkeley** [comment]
The issue was `params` needed to be stringified `JSON.stringify(params)`, so nothing to do with superagent.
