### ISSUE TITLE
i'm using 'res.ok' to check if the request is success or not, now 'res' is undefined sometimes

### ISSUE THREAD

**Issue by dandybreath** [visionmedia/superagent#760]
```
/var/www/html/game/game_server.js:163
                if (res.ok) {
                       ^
TypeError: Cannot read property 'ok' of undefined
    at submit_card_callback (/var/www/html/game/game_server.js:163:24)
    at /var/www/html/game/parameter.js:39:13
    at Request.callback (/var/www/html/game/node_modules/superagent/lib/node/index.js:781:12)
    at ClientRequest.<anonymous> (/var/www/html/game/node_modules/superagent/lib/node/index.js:736:10)
    at ClientRequest.emit (events.js:95:17)
    at Socket.socketErrorListener (http.js:1552:9)
    at Socket.emit (events.js:95:17)
    at net.js:834:16
    at process._tickCallback (node.js:442:13)
```

**Comment by defunctzombie** [comment]
you need to check if there is an error

**Comment by dandybreath** [comment]
ok, i re-read the doc about error handling.
fortunately i wrapped it on a single function so i just need to change that.

it's hard to check error since it occured after the apps running more than 12 hr iirc.
