### ISSUE TITLE
image buffer

### ISSUE THREAD

**Issue by halfcrazy** [visionmedia/superagent#766]
As shown below, there's something wrong with the call to myOcr.ocr, but i've checked the param passed to the function call, i found it indeed a object with buffer type.
my node version is 4.1.2
and superagent version is 1.2.0

<Buffer ff d8 ff e0 00 10 4a 46 49 46 00 01 01 00 00 01 00 01 00 00 ff db 00 43 00 08 06 06 07 06 05 08 07 07 07 09 09 08 0a 0c 14 0d 0c 0b 0b 0c 19 12 13 0f ... >
/root/workspace/city_fetcher/common/simulate_login.js:33
        myOcr.ocr(res1.body, function(err2, result) {
              ^

TypeError: Argument 1 must be an object of type Buffer
    at TypeError (native)
    at /root/workspace/city_fetcher/common/simulate_login.js:33:15
    at Request.callback (/root/workspace/city_fetcher/node_modules/superagent/lib/node/index.js:785:12)
    at /root/workspace/city_fetcher/node_modules/superagent/lib/node/index.js:929:14
    at IncomingMessage.<anonymous> (/root/workspace/city_fetcher/node_modules/superagent/lib/node/parsers/image.js:8:7)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:430:9)
    at process._tickCallback (node.js:344:17)

'''
      var req = request.get(validateImgUrl);
      req.set('Cookie', Cookies);
      req.end(function(err1, res1) {
        if (err1) {
          return callback(err1);
        }
        console.log(res1.body);
        var myOcr = new tesseract.OcrEio();
        myOcr.ocr(res1.body, function(err2, result) {
          if (err2) {
            return callback(err2);
          } else {
'''

**Comment by pornel** [comment]
Sorry, that's an old issue. From the log I don't see a problem, and I don't know about OcrEio API.
