### ISSUE TITLE
Node 4 support

### ISSUE THREAD

**Issue by John-Steidley** [visionmedia/superagent#773]
I'm wondering what the story is for support for Node 4. Do you currently support it? Do you plan to in the future?

I'm currently trying to track down an issue that I'm having in one of my dependencies. Supertest (not superagent) is causing an issue which starts appearing in Node 0.11.14. During my investigation I noticed that the superagent tests are currently failing on Node 4. (I haven't tried any IO.js versions, but it does pass on 0.12.7)

```
$ node -v 4.0.0
$ npm test
...
149 passing (2s)
1 failing

1) request req.redirects(n) should alter the default number of redirects to follow:
     Uncaught AssertionError: expected 'Found. Redirecting to /movies/all/0' to match /Moved Temporarily/
      at Assertion.prop.(anonymous function) (/Users/John/code/superagent/node_modules/should/lib/should.js:60:14)
      at /Users/John/code/superagent/test/node/redirects.js:232:25
      at Request.callback (/Users/John/code/superagent/lib/node/index.js:797:3)
      at IncomingMessage.<anonymous> (/Users/John/code/superagent/lib/node/index.js:990:12)
      at emitNone (events.js:72:20)
      at IncomingMessage.emit (events.js:166:7)
      at endReadableNT (_stream_readable.js:893:12)
      at doNTCallback2 (node.js:429:9)
      at process._tickCallback (node.js:343:17)
```

**Comment by jordansexton** [comment]
FWIW I use node 4.2.1 with superagent 1.4.0 on both the client and server without apparent issue. I don't know about the tests, however.
