### ISSUE TITLE
Test failure (res.toError() should return an Error)

### ISSUE THREAD

**Issue by chrisbartley** [visionmedia/superagent#790]
When doing a `make test`, one of the tests is failing.  Here it is with Node 5.0.0:

```
  1) res.toError() should return an Error:
     Uncaught AssertionError: err.status == 400
      at /Users/chris/Downloads/superagent-latest/superagent/test/node/toError.js:20:7
      at Request.callback (/Users/chris/Downloads/superagent-latest/superagent/lib/node/index.js:785:12)
      at Stream.<anonymous> (/Users/chris/Downloads/superagent-latest/superagent/lib/node/index.js:993:12)
      at emitNone (events.js:72:20)
      at Stream.emit (events.js:166:7)
      at Unzip.<anonymous> (/Users/chris/Downloads/superagent-latest/superagent/lib/node/utils.js:108:12)
      at emitNone (events.js:72:20)
      at Unzip.emit (events.js:166:7)
      at endReadableNT (_stream_readable.js:905:12)
      at doNTCallback2 (node.js:450:9)
      at process._tickCallback (node.js:364:17)
```

Similarly, with Node 0.12.7:

```
  1) res.toError() should return an Error:
     Uncaught AssertionError: err.status == 400
      at /Users/chris/Downloads/superagent-latest/superagent/test/node/toError.js:20:7
      at Request.callback (/Users/chris/Downloads/superagent-latest/superagent/lib/node/index.js:785:12)
      at Stream.<anonymous> (/Users/chris/Downloads/superagent-latest/superagent/lib/node/index.js:993:12)
      at Stream.emit (events.js:129:20)
      at Unzip.<anonymous> (/Users/chris/Downloads/superagent-latest/superagent/lib/node/utils.js:108:12)
      at Unzip.emit (events.js:129:20)
      at _stream_readable.js:908:16
      at process._tickCallback (node.js:355:11)
```

**Comment by chrisbartley** [comment]
[sigh] The failing test is making a request to localhost:8888, assuming nothing's listening. But! I happen to have a server listening on localhost:8888, so the test "fails". I'd suggest documenting in the test description that it's making a request to localhost:8888.

**Comment by focusaurus** [comment]
We can certainly use a weirder port to make this less likely.
