### ISSUE TITLE
TypeError: .set is not a function

### ISSUE THREAD

**Issue by littlee** [visionmedia/superagent#853]
latest version in npm (1.6.1)

```js
var r = require('superagent')
request.set('a', 'a').get('/some/path/').end();
```

```
TypeError: request.set is not a function
    at Object.<anonymous> (E:\Web\test.js:3:3)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3
```

**Comment by pornel** [comment]
You must start with `request[http_method]`, so nothing works until you do `request.get()`.

**Comment by littlee** [comment]
dang it, my fault
