### ISSUE TITLE
.field('key', true) passing boolean true as value breaks everything

### ISSUE THREAD

**Issue by afanasy** [visionmedia/superagent#994]
``` js
require('superagent').post('/').field('key', true).end()
```

```
> TypeError: Invalid non-string/buffer chunk
    at validChunk (_stream_writable.js:186:14)
    at Transform.Writable.write (_stream_writable.js:213:12)
    at FormData.ondata (stream.js:31:26)
    at emitOne (events.js:77:13)
    at FormData.emit (events.js:169:7)
```

**Comment by jcramer** [comment]
i have this same issue.  Its a problem for me because I receive an error from the server if I submit "true"
